# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2610e6553d194390a3bb783b3f88163c3a3094df5c6c772bce34e095f285c207fdc16bca3a774fa625bb2216552f810377b726e2e1e2fcfd1207ffbdd4f83f3

test:
  secret_key_base: 970e7ca3aea2e660866ecf3df87277a9cabe62b7a2b4149bacf1af32155974d3055538e8027bdfc06834d164b72cc7ed218bcbfffa377c4e6630a434897a747f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
